### ISSUE TITLE
Image from  docker hub   does not contain ENV variables for building zephyr

### ISSUE THREAD

**Issue by franciscomunoz** [zephyrproject-rtos/docker-image#14]
Downloaded image from docker hub:
https://hub.docker.com/r/zephyrprojectrtos/ci

to test our CI pipeline, and the hosted image does not contain the following env variables

113 # Set the locale
114 ENV ZEPHYR_TOOLCHAIN_VARIANT=zephyr
115 ENV ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-${ZSDK_VERSION}
116 ENV ZEPHYR_BASE=/workdir
117 ENV GNUARMEMB_TOOLCHAIN_PATH=/opt/toolchains/${GCC_ARM_NAME}

however, the ENV variables are there when I build the image using the Dockerfile. 
Is this the expected behaviour?

**Comment by nashif** [comment]
outdated
