### ISSUE TITLE
Dockerfile.ci: v0.26.0: PyYAML from renode python requirements conflicts with zephyr's one

### ISSUE THREAD

**Issue by avolkov-1221** [zephyrproject-rtos/docker-image#145]
Hello,

Renode requires hardcoded PyYAML == 6.0 while awscli and friends want PyYAML >= 5.4 and < 6.0, so an older PyYAML is suddenly installed, with probably unpredictable results in all Renode dependent tests.

AFAIS scripts/requirements-*.txt should be updated to use newer packages and hopefully avoid above problem.

**Comment by stephanosio** [comment]
> @stephanosio I think we should still remove `awscli`, do you know if `awscliv2` could replace it in CI workflows that require it?

As far as I can see, we are not using the `awscli` package directly anywhere in our CI. I will send a patch to remove it (or migrate to `awscliv2`).

**Comment by stephanosio** [comment]
`awscli` will be removed in https://github.com/zephyrproject-rtos/docker-image/pull/147
