### ISSUE TITLE
bug: Dockerfile.ci: Unpredictable  vanilla clang version installed (was broken clang-15 installation in v0.26.0)

### ISSUE THREAD

**Issue by avolkov-1221** [zephyrproject-rtos/docker-image#149]
Hello,

Unfortunately last release has fixed the clang-15 problem, but introduce new regression: version of clang is now vanilla 'latest', but not defined by LLVM_VERSION variable. This is due to missed following url modification in the Dockerfile:

 `- echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main" | tee /etc/apt/sources.list.d/llvm-official.list && \`
 `+ echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-${LLVM_VERSION} main" | tee /etc/apt/sources.list.d/llvm-official.list && \ `

**llvm-toolchain-jammy** is a link to the 'latest stable', not predefined version. So version 17 (latest stable for now) will installed.

**Comment by stephanosio** [comment]
You seem to be looking at an outdated copy of the repository. Please re-open if you think this is still an issue.
