### ISSUE TITLE
Hardcoded UID and GID might not match host user

### ISSUE THREAD

**Issue by dimka-rs** [zephyrproject-rtos/docker-image#19]
Hardcoded UID and GID make impossible to modify attached volume for users with UID/GID != 1000.
I suggest adding UID/GID args like this:
https://stackoverflow.com/questions/44683119/dockerfile-replicate-the-host-user-uid-and-gid-to-the-image

**Comment by galak** [comment]
@dimka-rs a PR would be welcome.

**Comment by nashif** [comment]
fixed now
