### ISSUE TITLE
"west" Error on Build

### ISSUE THREAD

**Issue by melonchucker** [zephyrproject-rtos/docker-image#35]
When I launch using the prebuilt image and mount a fresh clone of the Zephyr repo into "workdir", I get an error when I run the "west build" command.  It gives me an error saying I have an invalid build choice and from reading it looks this usually occurs when a west project hasn't been set up.  There is a west.yml file and the ZEPHYR_BASE env variable is set to /workdir but when I run "west update" I get an error saying no west workspace is found in the /workdir directory.

```
user@0bcb1e85f710:/workdir$ west build -p auto -b qemu_x86 samples/hello_world/
usage: west [-h] [-z ZEPHYR_BASE] [-v] [-V] <command> ...
west: error: argument <command>: invalid choice: 'build' (choose from 'init', 'update', 'list', 'manifest', 'diff', 'status', 'forall', 'help', 'config', 'topdir', 'selfupdate')`

```
```
user@0bcb1e85f710:/workdir$ west update
FATAL ERROR: no west workspace found from "/workdir"; "west update" requires one.
Things to try:
  - Change directory to somewhere inside a west workspace and retry.
  - Set ZEPHYR_BASE to a zephyr repository path in a west workspace.
  - Run "west init" to set up a workspace here.
  - Run "west init -h" for additional information.
```

**Comment by stephanosio** [comment]
Closing stale issue; please re-open if this is still an issue.
