### ISSUE TITLE
Container for v0.13 not present on hub.docker.com

### ISSUE THREAD

**Issue by MitterdorferMathias** [zephyrproject-rtos/docker-image#50]
Is there a reason why the v0.13 tag is not present anymore on 
https://hub.docker.com/r/zephyrprojectrtos/zephyr-build/tags?page=1&ordering=last_updated

If not, could you please rebuild / deploy the container?

**Comment by galak** [comment]
> Is there a reason why the v0.13 tag is not present anymore on
> https://hub.docker.com/r/zephyrprojectrtos/zephyr-build/tags?page=1&ordering=last_updated
> 
> If not, could you please rebuild / deploy the container.

Did this tag ever exist?

**Comment by MitterdorferMathias** [comment]
@galak Hi, 

I do not know, but I suppose not. I thought there is some automatic build / deployment of tags (which is probably not the case)

So could somebody please add the v0.13 Container to Docker Hub?

**Comment by galak** [comment]
Not sure how the v0.13 got tagged, I've created a v0.14 tag that should get published with the latest commit.

**Comment by MitterdorferMathias** [comment]
Our build container is based on this container. 
Only v0.13 would be appropriate for our current codebase (v0.14 or v0.12) would not work.

Github Actions were added after the v0.13 release (https://github.com/zephyrproject-rtos/docker-image/commit/55a6d9847a6ed742b6750e61e968028f15922e05), previously publishing was done by shippable.

Maybe it ist possible to get the container on Docker Hub (e.g. manually), otherwise we will create / store this container on our servers.

**Comment by galak** [comment]
Let me check with @nashif as I'm guessing he's the one that has pushed this to dockerhub in the past.

**Comment by nashif** [comment]
have not pushed tags for a while, the latest is always available as :latest.

**Comment by MitterdorferMathias** [comment]
@nashif 
We started our build container based on the `:latest` container. Currently we had to make some changes to our container, which broke the build (as also the `:latest` container changed). For our build the toolchain present in `v0.13` would be appropriate.

Could you please push the container to Docker Hub?

**Comment by MitterdorferMathias** [comment]
Ok, this seems to be no trivial task, as some packages listed in the Dockerfile (`pip`, ...) got updated in the meantime. We will find a solution for our purpose :+1:

**Comment by johngrey-dev** [comment]
> have not pushed tags for a while, the latest is always available as :latest.

latest is also not up-to-date with repos state. last commit updated to sdk 0.12.3. both v0.14 and latest build with sdk 0.12.0.
by the way:
* v0.14 is from Feb 17, 2021 at 4:50 pm 
* latest is from Feb 5, 2021 at 5:39 pm

so some tag was pushed lately. maybe its the last commit 632c85dcbbc8cc5c656faa37e05cbdfdfda81430 with changes to  .github/workflows/publish.yml

**Comment by nashif** [comment]
had to rebuild v0.13 with some fixes and pushed to docker, we should have v0.13 now. the latest was also pushed as 0.15 (and latest)
