### ISSUE TITLE
How to use this docker image?

### ISSUE THREAD

**Issue by windelbouwman** [zephyrproject-rtos/docker-image#62]
I have a project, which I can build like this:

```bash
$ cmake -B build -GNinja -DBOARD=nucleo_f429zi .
$ ninja -C build
```

Which docker image should I use to build this project, and how should I use it?

I tried this, but it did not work:

```bash
$ docker run --rm  --volume c:\git\my_project:/project zephyrprojectrtos/ci /bin/bash /project/build.sh
```

**Comment by stephanosio** [comment]
Closing stale issue; insufficient information
