### ISSUE TITLE
Docker image not correctly set up

### ISSUE THREAD

**Issue by hbjorgo** [zephyrproject-rtos/docker-image#73]
Hi. This is my first time trying out Zephyr. I'd love to start hacking, but I can't get it to work... I prefer running the development environment in a container, then everything is/should be correctly set up, and I don't need to install all the stuff on my computer.

I start a new docker container:
`docker run -ti -v $HOME/Work/zephyrproject:/workdir docker.io/zephyrprojectrtos/zephyr-build:latest`

Using the cli, I default to the `workdir` directory.
I run
`west init`
`cd zephyr`
`west update`
`west build -p auto -b esp32 samples/basic/blinky`
I get

> -- west build: generating a build system
Including boilerplate (Zephyr base): /workdir/zephyr/cmake/app/boilerplate.cmake
-- Application: /workdir/zephyr/samples/basic/blinky
-- Zephyr version: 2.6.99 (/workdir/zephyr), build: zephyr-v2.6.0-2270-g976c5fee289f
-- Found Python3: /usr/bin/python3.8 (found suitable exact version "3.8.10") found components: Interpreter
-- Found west (found suitable version "0.11.0", minimum required is "0.7.1")
-- Board: esp32
-- Cache files will be written to: /home/user/.cache/zephyr
CMake Error at /workdir/zephyr/cmake/verify-toolchain.cmake:70 (find_package):
  Could not find a configuration file for package "Zephyr-sdk" that is
  compatible with requested version "0.13".
The following configuration files were considered but not accepted:
/opt/toolchains/zephyr-sdk-0.12.4/cmake/Zephyr-sdkConfig.cmake, version: 0.12.4
Call Stack (most recent call first):
  /workdir/zephyr/cmake/app/boilerplate.cmake:548 (include)
  /workdir/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:24 (include)
  /workdir/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:35 (include_boilerplate)
  CMakeLists.txt:4 (find_package)
-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake -DWEST_PYTHON=/usr/bin/python3 -B/workdir/zephyr/build -S/workdir/zephyr/samples/basic/blinky -GNinja -DBOARD=esp32

Do I do something wrong, is the image not correctly set up, or is the documentation incorrect/poor?

**Comment by dauc** [comment]
It looks like the zephyr default tool chain changed to 0.13.0 ~10 days ago.  try `ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-0.13.0/ west build ...`. to target 0.13.0 (which happens to be installed on `zephyr-build:latest` already https://github.com/zephyrproject-rtos/docker-image/blob/5baf0c6ba07769f035c76eb62bbfcbfc3ebfeef5/Dockerfile#L4.

I _think_ the is to bump `ZSDK_VERSION` https://github.com/zephyrproject-rtos/docker-image/blob/5baf0c6ba07769f035c76eb62bbfcbfc3ebfeef5/Dockerfile#L3 to `0.13.0` but 🤷 .

**Comment by eastabrooka** [comment]
_**Is It ?**_ 

I have been building from the Dockerfile, and I have run into some issues with the docker build command failing. 

I feel that the upstream docker project has changed its filenames for the release accidentally. This may be causing some issues. 

![image](https://user-images.githubusercontent.com/11888681/132858238-4646e2eb-f111-4bbc-b43c-2c336a28a375.png)

**Comment by hbjorgo** [comment]
Any maintainer that can run it and fix it?

**Comment by galak** [comment]
esp isn't supported by the Zephyr SDK, this isn't a docker image issue.

**Comment by eastabrooka** [comment]
It isn't ?! 
[https://www.**zephyrproject.org**/zephyr-rtos-on-esp32/ ](https://www.zephyrproject.org/zephyr-rtos-on-esp32/ )
Anyway - I am going to stop bumping this Issue, and open a dedicated issue for my spot.

**Comment by galak** [comment]
> It isn't ?!
> [https://www.**zephyrproject.org**/zephyr-rtos-on-esp32/ ](https://www.zephyrproject.org/zephyr-rtos-on-esp32/)
> Anyway - I am going to stop bumping this Issue, and open a dedicated issue for my spot.

To be clear, Zephyr supports esp32, the "Zephyr SDK" does NOT.  I believe the `west espressif update` step pulls in the libraries and toolchains from espressif needed to build the esp32 support.

**Comment by hbjorgo** [comment]
If I recall correctly, I also tried with `reel_board` as in the ["Getting started" guide](https://docs.zephyrproject.org/1.14.1/getting_started/index.html#build-the-application).

**Comment by stephanosio** [comment]
Outdated issue
