### ISSUE TITLE
Broken Link in Docker Script ? 

### ISSUE THREAD

**Issue by eastabrooka** [zephyrproject-rtos/docker-image#75]
Hi, 

I am a newcomer to Zephyr, but in trying to get the latest SDK via the Docker Image I have run into some issues. 

In the Docker File - We call WGET with this string : https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${ZSDK_VERSION}/zephyr-sdk-${ZSDK_VERSION}-x86_64-linux-setup.run

So - I am trying to build something that requires 0.13.0. 

When using the Docker script as currently in this repo This URL is called. This pulls down the 1.1GB File for Zephyr SDK. 

ARG ZSDK_VERSION=0.12.4 
https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.12.4/zephyr-sdk-0.12.4-x86_64-linux-setup.run

But when you replace the 0.12.4 with 0.13.0. - It fails. 
ARG ZSDK_VERSION=0.13.0
https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.13.0/zephyr-sdk-0.13.0-x86_64-linux-setup.run

So - > 

![132858238-4646e2eb-f111-4bbc-b43c-2c336a28a375](https://user-images.githubusercontent.com/11888681/133314562-1d73b656-5cc0-42fe-84a0-603ecfefcfd0.png)

It looks like in making the latest V0.13 release, the maintainers have swapped the OS - Architecture nomenclature around, breaking this Docker Script. 

Can someone confirm that issue for me ?

I saw another user was having a *Similar* issue over here https://github.com/zephyrproject-rtos/docker-image/issues/73. 
But I feel that this was distinct enough to warrant opening a fresh issue for this. 

( When I hardcode the path with the flipped OS - Arch flags, The Dockerfile works fine for 0.13.0. ) 
Thanks,

**Comment by stephanosio** [comment]
Outdated issue
