### ISSUE TITLE
arm-none-eabi-gdb fails lacking libncurses.so.5

### ISSUE THREAD

**Issue by 0Grit** [zephyrproject-rtos/docker-image#80]
Trying to debug a target from the container and `arm-none-eabi-gdb` fails

`arm-none-eabi-gdb: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory'

**Comment by stephanosio** [comment]
Marking it `wontfix` since we will soon be removing the GNU Arm Embedded toolchain from the these images (#92).
